### ISSUE TITLE
updateR - Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by ameer-kanaan** [talgalili/installr#134] opened 2019-09-20 20:27 UTC
HELP! It is making me crazy.

When using `updateR()` or `updateR(TRUE)`, I'm receiving this error:

> Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   InternetOpenUrl failed: 'A connection with the server could not be established'

I've allowed access through the firewall for RStudio and R. I've stopped my anti-virus. I'm also running as an Administrator.

I also tried `options(download.file.method = "libcurl")`.

None has helped.

`sessionInfo()` is:

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
> [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
> [5] LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] installr_0.22.0 stringr_1.4.0  
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.5.1 magrittr_1.5   tools_3.5.1    yaml_2.2.0     stringi_1.4.3 
> 

As you probably know, `setInternet2(TRUE)` in the newer versions of R is _defunct_, so it is no fix.

**Comment by talgalili** [comment] 2019-09-21 10:43
What happens if you run:
download.file("https://cran.r-project.org/", destfile="temp.txt")
?

**Comment by abubelinha** [comment] 2020-04-13 19:26
I have exactly the same problem

@talgalili when I run the `download.file` command you mentioned, it works:

```
> download.file("https://cran.r-project.org/", destfile="temp.txt")
probando la URL 'https://cran.r-project.org/'
Content type 'text/html' length 850 bytes
downloaded 850 bytes

```
Looks like it worked (R can make https connection and download text file).

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] installr_0.23.0 stringr_1.4.0  

loaded via a namespace (and not attached):
[1] compiler_3.6.1 magrittr_1.5   tools_3.6.1    stringi_1.4.3 

```

BTW ... I have tried to install a fresh R 3.6.3 in another path, and after loading `installr` and calling `updateR()` the problem is still there (of course there is nothing to update, but R gives the same error message -in Spanish-):

```
> updateR()
Error in file(con, "r") : no se puede abrir la conexión
Además: Warning message:
In file(con, "r") :
  fallo en InternetOpenUrl: 'Error en el soporte del canal seguro'

```

**Comment by talgalili** [comment] 2022-06-05 12:45
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.

**Closed by talgalili** 2022-06-05 12:45 UTC
